[package]
name = "gpu_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
image = "0.25"
bytemuck = "1.14"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

# Workspace dependency
video_kit_common = { path = "../video_kit_common" }
