// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single subtitle/caption with timing information
 * This is a simplified view of Deepgram's Utterance for subtitle export
 */
export type Subtitle = { 
/**
 * Start time in seconds
 */
start: number, 
/**
 * End time in seconds  
 */
end: number, 
/**
 * The spoken text
 */
text: string, 
/**
 * Confidence score (0.0 - 1.0)
 */
confidence: number, 
/**
 * Speaker identification (if available)
 */
speaker: string | null, 
/**
 * Language detected/used
 */
language: string | null, };
