[package]
name = "sam2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.8"