// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Properties for mask outline features
 */
export type MaskOutlineProperties = { id: number, area: number, has_holes: boolean, hole_count: number, perimeter: number, };
