// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDimensions } from "./ImageDimensions";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Response containing outline extraction results
 */
export type OutlineResponse = { shapes_count: number, image_dimensions: ImageDimensions, geojson: JsonValue, };
